list: $/longbang/ooctober/models/multilanguage/columns.yaml
modelClass: Longbang\Ooctober\Models\Multilanguage
title: Multilanguage
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'longbang/ooctober/multilanguage/update/:id'
