plugin:
    name: 'longbang.cms::lang.plugin.name'
    description: 'longbang.cms::lang.plugin.description'
    author: longbang
    icon: oc-icon-codepen
    homepage: ''
permissions:
    longbang.key:
        tab: 'longbang.cms::lang.longbang_cms_config_multilanguage.key'
        label: 'longbang.cms::lang.vc.key'
navigation:
    VC:
        label: 'longbang.cms::lang.vc.menu'
        url: longbang/cms/configmultilanguage
        icon: icon-windows
        sideMenu:
            multilanguage.blade:
                label: 'longbang.cms::lang.longbang_cms_config_multilanguage.blade'
                url: blade/languages
                icon: icon-stack-overflow
                attributes:
                    - vc_jump_BladeIndex
